### ISSUE TITLE
Write Up workflow for showing the pyttb GitHub workflow

### ISSUE THREAD

**Issue by DeepBlockDeepak** [sandialabs/pyttb#121]
The pyttb workflow process might be tricky for brand new contributors to the project. Let's use a guide similar to the CONTRIBUTING.md explanation, but for the GitHub workflow process. Assigning to Nick, to see if he wants to add. Feel free to assign back to me.

Here's my initial stab:

# Python Tensor Toolbox GitHub Workflow Guide

## Creating an Issue and Pull Request

If you want to propose a change, follow the steps below:

1. **Create an issue**

    - Go to the [issues tab](https://github.com/sandialabs/pyttb/issues) of the PYTTB GitHub repository.

    - Click on the `New issue` button.

    - Fill in the title and the description of the issue, then click `Submit new issue`.

1. **Create a new branch for the issue**

    - After creating an issue, navigate to that new issue's page.

    - Go to the `Development` tab on the right side of the page.

    - Click on `Create a new branch`.

1. **Make updates locally for the branched issue**

    - `If Working in terminal`:

        - In your local environment, checkout to the new branch:

        ```bash
        git checkout -b <your-new-branch-name>
        ```

        - Make the necessary updates in the code.

        - Stage and commit your changes:

        ```bash
        git add .

        git commit -m "your commit message"
        ```
    
    - `If working in VSCode (use Source Control view)`:
        - Click on the branch name in the bottom-left corner and select the new branch you just created from the drop-down that appears.

        - Make the necessary updates in the code.

        - Stage your changes by clicking on the `+` icon next to each file in the `Source Control` view, or use the `+` button at the top to stage all changes. THen commit your changes with a relevant message.

1. **Push your changes and create a pull request**

    - Push your changes to the remote repository:

    ```bash
    git push origin <your-new-branch-name>
    ```

    - Go to the [main page](https://github.com/sandialabs/pyttb) of the PYTTB GitHub repository.

    - Click on the `Pull request` tab, then click on `New pull request`.

    - Select your branch from the `compare` dropdown menu, then click `Create pull request`.

1. **Review Process**

    - Wait for the Github CI tests to pass. If any test fails, review your code make necessary changes, and push your code again.

    - Once all checks have passed, select a reviewer by clicking on the `Reviewers` tab on the right side of the pull request page and selecting a team member.

    - Address any comments or requested changes from the review process. Push any additional changes to the same branch.

    - Once your changes are approved, the repository admin will merge your pull request.

**Comment by ntjohnson1** [comment]
Thanks for putting this together! Here are some thoughts. In my opinion it is easier for me to assign this to you and you can open a PR and assign me to review then we can iterate from there. As long as you place every sentence on a new line in the markdown I can basically do line edits through the github review system.

Ideally anywhere we can we should generalize or point to external resources since most of these instructions aren't related to opinions or preferences on our part. See pydantics contributing guide as one comprehensive but terse option https://docs.pydantic.dev/latest/contributing/ there are many other large open source projects we could probably take inspiration from. I think a lot of the github specifics are already handled in githubs getting started contributing page https://docs.github.com/en/get-started/quickstart/contributing-to-projects

Some notes on the first draft (I put my thoughts in parenthesis throughout, I aimed to err on the side of overly verbose to avoid ambiguity)

# Python Tensor Toolbox GitHub Workflow<s>Guide</s>

## Creating an Issue and Pull Request

If you want to propose a change, follow the steps below:


1. <s>**Create an issue** </s> (Ideally, we add an issues template and just point people to our issues board which is fairly self explanatory. If we HAVE to provide details just a link to githubs page discussing issues https://github.com/features/issues)

    - ---snipped all the bullets---

1. <s>**Create a new branch for the issue** </s> (overly specific, I don't think general users can create a branch this way and the standard flow is to instead fork the repo, and then open a PR to merge back to us, we could include a link to the github getting started here as well or maybe we can just reference it once at the very beginning)

    - ---snipped bullets again---

1. <s>**Make updates locally for the branched issue** </s> (I think we should remove this entirely. What is in the Contributing doc already aims to get people started from a fresh clone. The details here aren't even github but rather the basics on branching with git. If we wanted to be super friendly to contributors who don't have a git background we COULD include external links for each step. But I don't want us to maintain docs on how to use git since that is quite general)

    - ---snip---

1. **Push your changes and create a pull request** (I think this doesn't really need elaboration but could again include an external link)

    - NOTE: In addition to the issues template which is higher priority it might also be nice for a minimal PR template too, see this for a variety of github niceties https://github.com/sandialabs/pyttb/community
    - NOTE: Since this should ultimately merge with the CONTRIBUTING GUIDE we could mention that people should be able to run tests locally first to confirm tests on CI should pass if their branch is up to date with main

1. **Review Process**

    - Wait for the Github CI tests to pass. If any test fails, review your code make necessary changes, and push your code again.

    - Once all checks have passed, select a reviewer by clicking on the `Reviewers` tab on the right side of the pull request page and selecting a team member. (I don't know if general users have permissions to assign a reviewer themselves. That probably is worth checking and if general users with no special permissions on the repo can't select a reviewer we should figure out instructions here)

    - Address any comments or requested changes from the review process. Push any additional changes to the same branch.

    - Once your changes are approved, the repository admin will merge your pull request.
