### ISSUE TITLE
Determine if `end()` is necessary in pyttb classes

### ISSUE THREAD

**Issue by dmdunla** [sandialabs/pyttb#161]
Do we the `end()` methods in pyttb classes?

The `end()` method is TTB for MATLAB is used to identify the index of the last element of a tensor using linear indexing or the last index along a dimension when using subscript indexing. 

`numpy` , which is used for most data objects in pyttb classes, supports negative indexing but in a different way than what `end()` does.

Should we implement `end()` methods that wrap `numpy` negative indexing (e.g., `X[-1,-1,-1]` for subscript indexing or `X.flat[-1]` for linear indexing? Or remove the `end()` methods?

**Comment by ntjohnson1** [comment]
I think we should avoid using `end()` for all indexing operations since that's very unnatural for python. I believe our slicing support already handles negative values. I was just looking at an example from sptensor `X[110:, 110:, 115:].isequal(X[-10:, -10:, -5:])` from this PR https://github.com/sandialabs/pyttb/pull/152 (after I apply some fixes to the sptensor indexing but nothing specific to negative indices).

**Comment by tgkolda** [comment]
It looks like -1 should work fine in lieu of end. I would suggest to have some explanation of this in the documentation, especially for those transitioning from MATLAB.

**Comment by dmdunla** [comment]
Answered this question. Will use -1 indexing in lieu of `end()` in class methods.

Follow up:
- #179
