### ISSUE TITLE
Complete tutorial: `tensor`

### ISSUE THREAD

**Issue by dmdunla** [sandialabs/pyttb#162]
There are some TODO's listed in `tutorial/Tensors.ipynb` tutorial. The following issues should be closed before this issue can be closed:

- [x] #160 
- [x] #161 

Once the above issues are closed, update the corresponding unfinished examples in `tutorial/Tensors.ipynb`

**Comment by ntjohnson1** [comment]
FYI @DeepBlockDeepak if everyone agrees on the approach here https://github.com/sandialabs/pyttb/pull/174 that should close the two blocking items above. I will let you make the appropriate updates on the tutorials to resolve this ticket as a follow on. Trying to avoid too many people touching the tutorials at once since it seems like a variety of those pieces are still in flight.

**Comment by ntjohnson1** [comment]
Resolved in https://github.com/sandialabs/pyttb/pull/193
