### ISSUE TITLE
Complete tutorial: `sptensor`

### ISSUE THREAD

**Issue by DeepBlockDeepak** [sandialabs/pyttb#171]
There are some TODO's listed in the `tutorial/class_sptensor.ipynb` tutorial. The following issues should be closed before this issue can be closed:

- [x] #160 
- [x] #169  
- [x] #170

Once the above issues are closed, update the corresponding unfinished examples in `tutorial/class_sptensor.ipynb`

**Comment by ntjohnson1** [comment]
Similar note at tensor:

FYI @DeepBlockDeepak if everyone agrees on the approach here https://github.com/sandialabs/pyttb/pull/174 that should close two of the blocking items above. Then this should solve the third https://github.com/sandialabs/pyttb/pull/175.

I will let you make the appropriate updates on the tutorials to resolve this ticket as a follow on. Trying to avoid too many people touching the tutorials at once since it seems like a variety of those pieces are still in flight.

**Comment by ntjohnson1** [comment]
Resolved in https://github.com/sandialabs/pyttb/pull/193
