### ISSUE TITLE
`make install*` fails on Mac OSX

### ISSUE THREAD

**Issue by jeremy-myers** [sandialabs/pyttb#223]
Starting with macOS 12.3, [Apple no longer ships python](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes) and instead only ships python3. The calls to`make install`, `make install_dev`, `make install_docs` fail. It may not be obvious to Mac users how to get around this, since aliasing python to python3 is not a solution.

**Comment by dmdunla** [comment]
Can you add a (redacted) example of the fail?

From: Jeremy Myers ***@***.***>
Date: Tuesday, September 5, 2023 at 3:04 PM
To: sandialabs/pyttb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [sandialabs/pyttb] `make install*` fails on Mac OSX (Issue #223)

Starting with macOS 12.3, Apple no longer ships python<https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes> and instead only ships python3. The calls tomake install, make install_dev, make install_docs fail. It may not be obvious to Mac users how to get around this, since aliasing python to python3 is not a solution.

**Comment by jeremy-myers** [comment]
# Example
```
❯ make install
python -m pip install -e .
xcode-select: Failed to locate 'python', requesting installation of command line developer tools.
make: *** [install] Error 72```

# Aliasing fails
```
❯ which python
python: aliased to /usr/bin/python3
❯ make install
python -m pip install -e .
xcode-select: Failed to locate 'python', requesting installation of command line developer tools.
make: *** [install] Error 72
```

Updating command line developer tools does not solve the issue.

**Comment by dmdunla** [comment]
It looks like you have aliased python to your python3 install. This will only work for you in your shell in which you aliased this.

You may want to create a symlink from /usr/local/bin/python to /usr/bin/python3 (I do not think you can change /usr/bin without disabling SSV). The symlink should work from any shell (including ones invoked via make).

Although this may fix your issue, this should be documented if aliases do not work with make.

From: Jeremy Myers ***@***.***>
Date: Tuesday, September 5, 2023 at 3:12 PM
To: sandialabs/pyttb ***@***.***>
Cc: Dunlavy, Danny ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [sandialabs/pyttb] `make install*` fails on Mac OSX (Issue #223)
Example

❯ make install

python -m pip install -e .

xcode-select: Failed to locate 'python', requesting installation of command line developer tools.

make: *** [install] Error 72```



# Aliasing fails

❯ which python
python: aliased to /usr/bin/python3
❯ make install
python -m pip install -e .
xcode-select: Failed to locate 'python', requesting installation of command line developer tools.
make: *** [install] Error 72



Updating command line developer tools does not solve the issue.

**Comment by jeremy-myers** [comment]
That is a workaround. However, /usr/local/bin/python exists and my guess is that Apple probably set it alias to /usr/bin/python3. One can change it, but it may need to be reset whenever macOS is updated. This should be called out in the documentation. I'm working on additions to the README that include this.

**Comment by dmdunla** [comment]
If /usr/local/bin/python exists and xcode/make cannot find that, that seems like a problem, too. Or does that point to python2?

From: Jeremy Myers ***@***.***>
Date: Tuesday, September 5, 2023 at 4:09 PM
To: sandialabs/pyttb ***@***.***>
Cc: Dunlavy, Danny ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [sandialabs/pyttb] `make install*` fails on Mac OSX (Issue #223)

That is a workaround. However, /usr/local/bin/python exists and my guess is that Apple probably set it alias to /usr/bin/python3. One can change it, but it may need to be reset whenever macOS is updated. This should be called out in the documentation. I'm working on additions to the README that include this.

**Comment by jeremy-myers** [comment]
The former. /usr/local/bin/python points to /usr/bin/python3 by default. Python2 is not shipped with macOS >= 12.3.

**Comment by dmdunla** [comment]
If you unalias your python alias, does it work? I think the alias is the real culprit here, when called from within makefiles.

From: Jeremy Myers ***@***.***>
Date: Tuesday, September 5, 2023 at 4:15 PM
To: sandialabs/pyttb ***@***.***>
Cc: Dunlavy, Danny ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [sandialabs/pyttb] `make install*` fails on Mac OSX (Issue #223)

The former. /usr/local/bin/python points to /usr/bin/python3 by default. Python2 is not shipped with macOS >= 12.3.

**Comment by dmdunla** [comment]
I am for removing the Makefile, as the contributing docs already state the commands for the different dev installs.

**Comment by ntjohnson1** [comment]
I think for full coverage we should:
1. Remove the make file
2. Update the readme/documentation to say how to install for a user (I didn't see that anywhere obvious)
3. Update the contributing documentation on how to run the sphinx build locally since that was the only thing in the make file before (we could probably add this as a pytest under a `docs` marker for ease of use)
