### ISSUE TITLE
Documentation recommendations

### ISSUE THREAD

**Issue by jeremy-myers** [sandialabs/pyttb#227]
# Class `ktensor`
- [x]  `normalize()`: Explicitly define order between normalizing and absorbing weights.
- [x] `score()`: Add new line after `max_weights`
- [x] `tovec()`: Add description that this is complement of `from_vector()`
- [x] `ttv()`: Define the expected behavior when `dims == exclude_dims` (should an error be thrown?).
- [x] `ttv()`: Clarify the following: "“If the shape of the vector is = (I,1), then the length of dimension *dims* of the pyttb.ktensor must be I." Here is an example that shows why this is confusing:
```
>>> rank = 2
>>> shape = (2,3,4)
>>> data = np.arange(1, rank*sum(shape)+1)
>>> weights = 2*np.ones(rank)
>>> weights_and_data = np.concatenate((weights,data),axis=0)
>>> K = ttb.ktensor.from_vector(weights_and_data[:], shape, True)
>>> v0 = np.array([1,1,1])
>>> v2 = v0[:,np.newaxis]
>>> v2.shape
(3, 1)
>>> dims = 1
>>> K2 = K.ttv(v2,dims=dims)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyttb/pyttb/ktensor.py", line 1964, in ttv
    assert False, "Multiplicand is wrong size"
AssertionError: Multiplicand is wrong size
```
In the above, `v2` has shape `(I,1)` and the tensor dimension *dims* also has dimension `I`. The wording in the documentation suggests one could pass a `(I,1)` vector, but only `(I,)` and `(1,I)` vectors return without error.

# Class `tensor`
- [x] `issymmetric()`: Is version required?
- [x] `symmetrize()`: Is version is required?

**Comment by ntjohnson1** [comment]
Two notes:
* When we fix the docs we should update `AssertionError: Multiplicand is wrong size` to be more descriptive about expectation vs observation.

> Define the expected behavior when dims == exclude_dims

Yes because ktensor.ttv calls tt_dimscheck which should raise [here](https://github.com/sandialabs/pyttb/blob/054b721e6284bd6d7882c81db6c380dfb104ea57/pyttb/pyttb_utils.py#L168). Did you see different behavior? Agreed we should make the docs clearer that dims and exclude_dims are mutually exclusive.

**Comment by jeremy-myers** [comment]
@ntjohnson1 No error is thrown:
```
>>> K.ttv(v0,dims=1)
ktensor of shape (2, 4)
weights=[36. 54.]
factor_matrices[0] =
[[1. 3.]
 [2. 4.]]
factor_matrices[1] =
[[11. 15.]
 [12. 16.]
 [13. 17.]
 [14. 18.]]
>>> K.ttv(v0,dims=1,exclude_dims=1)
ktensor of shape (2, 4)
weights=[36. 54.]
factor_matrices[0] =
[[1. 3.]
 [2. 4.]]
factor_matrices[1] =
[[11. 15.]
 [12. 16.]
 [13. 17.]
 [14. 18.]]
```

**Comment by ntjohnson1** [comment]
Great find!
[This](https://github.com/sandialabs/pyttb/blob/054b721e6284bd6d7882c81db6c380dfb104ea57/pyttb/ktensor.py#L1956) line should be `return self.ttv([vector], dims, exclude_dims)`. Lets skip opening a new ticket for that and have it be a part of this one since it is a one liner.

For any `v` that is a single vector rather than a list of vectors we currently ignore `exclude_dims` entirely. Exclude dims only makes sense with a single vector when `K.ndims==2` but we should still fix this.

Example for the general case I was expecting to have global coverage:
```python
# snip same setup
>>> v1 = np.array([1,1,1,1])
>>> K.ttv([v0, v1], exclude_dims=0)
# works
>>> K.ttv([v0, v1], dims=np.array([1,2]))
# matches
>>> K.ttv([v0, v1], dims=0, exclude_dims=0)
# snip traceback details
ValueError: Either specify dims to include or exclude, but not both
```

**Comment by ntjohnson1** [comment]
>  issymmetric(): Is version required?
 symmetrize(): Is version is required?
 
 I don't understand these two. In the documentation they are keyword arguments with defaults set to `None` and the parameter doc string says any non-None value will call non-default old version of the method. Can you clarify the confusion?

**Comment by jeremy-myers** [comment]
> > issymmetric(): Is version required?
> > symmetrize(): Is version is required?
> 
> I don't understand these two. In the documentation they are keyword arguments with defaults set to `None` and the parameter doc string says any non-None value will call non-default old version of the method. Can you clarify the confusion?

I could have been clearer:
```
>>> X = ttb.tensor.from_function(lambda a_shape: np.ones(a_shape), (2,2))
>>> is_sym, diffs, perms = X.issymmetric(grps=np.arange(X.ndims), version=None, return_details=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot unpack non-iterable bool object
```
My comment about `symmetrize()` can be ignored.
