### ISSUE TITLE
Include pre-commit in dev requirements?

### ISSUE THREAD

**Issue by dmdunla** [sandialabs/pyttb#280]
A discussion arose in #276 regarding `pre-commit`, which is currently supported but optional for `pyttb` developers.

Should we consider making this a requirement? What are the pros and cons of making it a requirement? Can we enforce it as a dev requirement?

**Comment by dmdunla** [comment]
I see. So, the CI test will block the merge if there are problems in the notebooks that do not conform to our use of `nbstripout`. And that should suffice for protecting commits with cruft we do not want.

**Comment by ntjohnson1** [comment]
That's my current opinion. We call out pre-commit as an option for people that find it convenient, but if there's any issue configuring pre-commit then it isn't strictly a dev blocker.

**Comment by ntjohnson1** [comment]
I changed my mind on this. I think adding the pre-commit package by default makes sense, then installing the hooks is optional. That probably provides the same flexibility as today but if people want the added ergonomics they can add the hooks. If someone complains because of some weird unexpected edge case we can backtrack.
