### ISSUE TITLE
1D tensor not displayed correctly

### ISSUE THREAD

**Issue by tgkolda** [sandialabs/pyttb#340]
When I display a 1D tensor, it has a spurious comma in the shape and is printed in row rather than column orientation:
Code:
```
data = np.array([5,7,8,1,3,9,5,3,5,2,8,4,5,1,7,2,9,4,7,7,8,1,3,5]);
X = ttb.tensor(data, (3, 4, 2));
print("X[1, :, 1] =\n", X[1, :, 1])
```
Output:
```
X[1, :, 1] =
 tensor of shape (4,)
data[:] =
[1 9 7 3]
```

Compare to MATLAB:

```
X = tensor([5,7,8,1,3,9,5,3,5,2,8,4,5,1,7,2,9,4,7,7,8,1,3,5],[3 4 2]);
X(2,:,2)
```
Output:
```
ans is a tensor of size 4
	ans(:) = 
	     1
	     9
	     7
	     3
```

**Comment by ntjohnson1** [comment]
This is consistent with our documentation and numpy. We note that we follow the numpy convention for 1D tensors to be a row.

Numpy has three flavors of 1D arrays of length N with shape (N,1), (1,N), and (N,) corresponding to explicit row, explicit column and a flexible 1D vector that can serve either.

So I think this is conceptually aligned but visually different. Have you run into functional issues because of this or just stylistic?

**Comment by tgkolda** [comment]
In MATLAB, we ensure any 1D tensor (or fiber of a larger tensor) is explicitly a column array. This is partly because MATLAB has no concept of a 1D array. But it's also consistent with the ordering of tensor modes. A row vector is technically a 1 x N tensor, whereas a column vector is an N or N x 1 tensor. This contrast to what you're saying, so I'm a bit confused.

**Comment by tgkolda** [comment]
Also, where is this in the documentation?

**Comment by ntjohnson1** [comment]
RE: Confusion
I think my ordering wasn't consistent. What you described matches for numpy as well.
```python
>>> N = 4
>>> np.ones((N,))
array([1., 1., 1., 1.])
>>> np.ones((N,1))
array([[1.],
       [1.],
       [1.],
       [1.]])
>>> np.ones((1,4))
array([[1., 1., 1., 1.]])
```

I think unless there is a strong functional reason we've tried to align design choices to numpy style since that is by far the most popular array/scientific computing package in python. We can see if the true 1-D array causes any issues for use or if its mostly just a style difference (unless you already have an example to review)

**Comment by ntjohnson1** [comment]
Discussion on #350 appears to subsume this so closing here so only tracking in one location
