### ISSUE TITLE
Add black and isort across the repo

### ISSUE THREAD

**Issue by ntjohnson1** [sandialabs/pyttb#59]
An initial follow up to https://github.com/sandialabs/pyttb/pull/54 to run autoformatting to bundle some churn together.
Run black and isort then enforce them for automated testing.

**Comment by dmdunla** [comment]
@ntjohnson1 Can you document the steps for manually running black and isort (and anything else for formatting you’re working on)? I know you’re moving toward an automated solution, but please document the steps. Either in the dev doc discussion or in a dev readme.

**Comment by nick-cerebras** [comment]
Ya. I can probably put together a quick contributing guide with some notes then we can iterate on that. As for how to run black and isort. We probably have a few options (can do all of them): add a make target, add a precommot hook, or just documenting that it will be enforced with how to run it manually. I would probably defer to what's easiest for your workflow to start.

The instructions for most of these is just to run the tool from root since the pyproject has the config. I started with black and isort since they just do the fix. For pylint and mypy they'll highlight if there is a bug that needs manual intervention.
```
Isort pyttb/ tests/
black pyttb/ tests/
```

**Comment by dmdunla** [comment]
Cool thanks! I like the idea of a pre-commit hook, but dev docs for manually running the formatting would be good to have on hand.
________________________________
From: Nick Johnson ***@***.***>
Sent: Friday, February 24, 2023 6:27:37 PM
To: sandialabs/pyttb ***@***.***>
Cc: Dunlavy, Daniel M ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [sandialabs/pyttb] Add black and isort across the repo (Issue #59)


Ya. I can probably put together a quick contributing guide with some notes then we can iterate on that. As for how to run black and isort. We probably have a few options (can do all of them): add a make target, add a precommot hook, or just documenting that it will be enforced with how to run it manually. I would probably defer to what's easiest for your workflow to start.

The instructions for most of these is just to run the tool from root since the pyproject has the config. I started with black and isort since they just do the fix. For pylint and mypy they'll highlight if there is a bug that needs manual intervention.

Isort pyttb/ tests/
black pyttb/ tests/

**Comment by ntjohnson1** [comment]
I added the dev doc to the open PR for now. The workflow is pretty simple so I punted on the pre-commit hook. It should be fairly simple to setup `pip install pre-commit` then add a yml file for configuring it (both isort and black have copy paste for it). I just saw on a quick google that sometime pycharm doesn't play nice with pre-commit so didn't have the motivation to verify it today.
